adding in an action to upload package and updating dist action to validate diff

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -49,7 +49,7 @@ jobs:
 
       # This will fail the workflow if the `dist/` directory is different than
       # expected.
-      - name: Compare Directories
+      - name: Compare dist/ Directories
         id: diff
         run: |
           if [ ! -d dist/ ]; then
@@ -66,7 +66,40 @@ jobs:
       # If `dist/` was different than expected, upload the expected version as a
       # workflow artifact.
       - if: ${{ failure() && steps.diff.outcome == 'failure' }}
-        name: Upload Artifact
+        name: Upload Artifacts from dist/ comparison
+        id: upload
+        uses: actions/upload-artifact@v5
+        with:
+          name: dist
+          path: dist/
+
+      - name: Build packages/bicep-deploy-common/dist/ Directory
+        id: build
+        run: |
+          cd packages/bicep-deploy-common
+          rm -Rf dist
+          npm run package
+
+      # This will fail the workflow if the `dist/` directory is different than
+      # expected.
+      - name: Compare packages/bicep-deploy-common/dist/ Directories
+        id: diff
+        run: |
+          if [ ! -d dist/ ]; then
+            echo "Expected dist/ directory does not exist.  See status below:"
+            ls -la ./
+            exit 1
+          fi
+          if [ "$(git diff --ignore-space-at-eol --text dist/*.js | wc -l)" -gt "0" ]; then
+            echo "Detected uncommitted changes after build. See status below:"
+            git diff --ignore-space-at-eol --text dist/*.js
+            exit 1
+          fi
+
+      # If `dist/` was different than expected, upload the expected version as a
+      # workflow artifact.
+      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
+        name: Upload Artifact from packages/bicep-deploy-common/dist/ comparison
         id: upload
         uses: actions/upload-artifact@v5
         with:
